# fly.toml app configuration file generated for financial-table on 2023-08-02T12:19:34-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "financial-table"
primary_region = "gru"

[env]
  SERVER_PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[checks]
  [checks.alive]
    type = "http"
    interval = "30s"
    timeout = "5s"
    path = "api/health-check"
